# Generated by Django 5.1.3 on 2026-04-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='idempotency_expires_79c374_idx',
            old_name='idempotency_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='ledger_entr_merchan_2b8c6e_idx',
            old_name='ledger_merchant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='ledger_entr_merchan_68130b_idx',
            old_name='ledger_merchant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_status_726895_idx',
            old_name='payouts_status_proc_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_merchan_a5cc5c_idx',
            old_name='payouts_merchant_created_idx',
        ),
    ]
